"""Public model contracts used by application and infrastructure layers."""

from customer_agent2.domain.models.chat import (
    ChatMessage,
    ChatModel,
    ChatRequest,
    ChatResult,
    ChatRole,
    ChatStreamChunk,
    TokenUsage,
)
from customer_agent2.domain.models.chunk import (
    ChunkDraft,
    ChunkingError,
    ChunkingErrorCode,
    ChunkingPolicy,
    ChunkingResult,
    TextTokenCodec,
)
from customer_agent2.domain.models.document import (
    DocumentError,
    DocumentErrorCode,
    DocumentFormat,
    DocumentIdentifier,
    DocumentParser,
    DocumentSource,
    IdentifiedDocument,
    ParsedBlock,
    ParsedBlockKind,
    ParsedDocument,
)
from customer_agent2.domain.models.embedding import (
    EmbeddingModel,
    EmbeddingRequest,
    EmbeddingResult,
)
from customer_agent2.domain.models.errors import ModelError, ModelErrorCode
from customer_agent2.domain.models.ingestion import (
    DocumentIngestionRequest,
    EmbeddingIndexConfiguration,
    IngestionAttempt,
    IngestionError,
    IngestionErrorCode,
    IngestionRepository,
    IngestionResult,
)
from customer_agent2.domain.models.rerank import (
    RerankDegradationReason,
    RerankDocument,
    RerankItem,
    RerankModel,
    RerankRequest,
    RerankResult,
)

__all__ = [
    "ChatMessage",
    "ChatModel",
    "ChatRequest",
    "ChatResult",
    "ChatRole",
    "ChatStreamChunk",
    "ChunkDraft",
    "ChunkingError",
    "ChunkingErrorCode",
    "ChunkingPolicy",
    "ChunkingResult",
    "DocumentError",
    "DocumentErrorCode",
    "DocumentFormat",
    "DocumentIdentifier",
    "DocumentIngestionRequest",
    "DocumentParser",
    "DocumentSource",
    "EmbeddingIndexConfiguration",
    "EmbeddingModel",
    "EmbeddingRequest",
    "EmbeddingResult",
    "IdentifiedDocument",
    "IngestionAttempt",
    "IngestionError",
    "IngestionErrorCode",
    "IngestionRepository",
    "IngestionResult",
    "ModelError",
    "ModelErrorCode",
    "ParsedBlock",
    "ParsedBlockKind",
    "ParsedDocument",
    "RerankDegradationReason",
    "RerankDocument",
    "RerankItem",
    "RerankModel",
    "RerankRequest",
    "RerankResult",
    "TextTokenCodec",
    "TokenUsage",
]
